micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
  io:
    services:
      eager-init: true
  application:
    name: micronautpoc
endpoints:
  all:
    sensitive: false

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/prosperas_1
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
      baselineOnMigrate: true
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
netty:
  default:
    allocator:
      max-order: 3
