micronaut:
  application:
    name: micronautpoc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ''
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
